### ISSUE TITLE
Deposit NST Balance Update to Zero 

### ISSUE THREAD

**Issue by cloud8little** [imua-xyz/price-feeder#18]
**Description**: Depoist 32ETH NST for two stakers, NST balance update to Zero. 

**Steps**
1. Start four validators network using https://github.com/cloud8little/ExocoreValidators,disable --exocore option. exocore binary: https://github.com/ExocoreNetwork/exocore/pull/277/commits/f94b350462a78bb7a643b027c03b6ef328cfe7b3
2. Replace all genesis file with [genesis_v7_delegationfix.json](https://github.com/user-attachments/files/18334021/genesis_v7_delegationfix.json) 
3. Start price feeder for four nodes separately.
price feeder binary: https://github.com/ExocoreNetwork/price-feeder/releases/tag/v0.2.2
5. Deposit 32ETH NST with staker 1, the validator is running.
`assetcli depositNST --rpcUrl http://localhost:9545 --staker 0xa53f68563D22EB0dAFAA871b6C08a6852f91d627 --amount 32000000000000000000 --privateKey C26A874A75B028638D477DDF31EB8627899CB505798DF70D2DD2A631F9CAE7A4  --pubkey 00000000000000000000000000000000000000000000000000000000001CDD66 --layerZeroID 40217`

6. Deposit 32ETH NST with staker 2, the validiator is slashed, effective balance is 31ETH. 
`assetcli depositNST --rpcUrl http://localhost:9545 --staker 0x0B34c4D876cd569129CF56baFAbb3F9E97A4fF42 --amount 32000000000000000000 --privateKey C26A874A75B028638D477DDF31EB8627899CB505798DF70D2DD2A631F9CAE7A4  --pubkey 000000000000000000000000000000000000000000000000000000000019FB60 --layerZeroID 40217`

7. Check Staker Info.
```
exocored q oracle show-staker-infos 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee_0x9d19 --node http://localhost:20000
staker_infos:
- balance_list:
  - balance: "0"
    block: "1456"
    change: ACTION_SLASH_REFUND
    index: "0"
    round_id: "49"
  staker_addr: ""
  staker_index: "1"
  validator_pubkey_list:
  - "0x000000000000000000000000000000000000000000000000000000000019fb60"
- balance_list:
  - balance: "0"
    block: "1456"
    change: ACTION_SLASH_REFUND
    index: "0"
    round_id: "49"
  staker_addr: ""
  staker_index: "0"
  validator_pubkey_list:
  - "0x00000000000000000000000000000000000000000000000000000000001cdd66"
```
8. The balance turn to 0.
9. Expected Result:  staker_index: "1" should have balance 31,  staker_index: "0" should have balance 32.
10. Attach the price feeder log for node1.
[pricefeeder_1.log](https://github.com/user-attachments/files/18334151/pricefeeder_1.log)
